import {expect,test} from '@playwright/test'
test('fixture agenda: tarefa sem prazo, compromisso de 30min, ocorrência e série no celular',async({page})=>{
  await page.setViewportSize({width:375,height:812})
  await page.clock.setFixedTime(new Date('2026-10-09T12:00:00Z'))
  await page.goto('/tests/browser/agenda-fixture.html')
  await page.getByLabel('Fuso da visualização').selectOption('America/Fortaleza')
  await page.getByRole('button',{name:'Nova tarefa',exact:true}).click()
  await page.getByLabel('Título da tarefa').fill('Tarefa fictícia')
  await page.getByLabel('Ambiente da tarefa').selectOption('environment-test')
  await page.getByRole('button',{name:'Salvar tarefa'}).click()
  await expect(page.getByText('Contexto fictício · Sem prazo')).toBeVisible()
  await page.getByRole('button',{name:'Editar tarefa'}).click()
  await page.getByLabel('Prazo (opcional)').fill('2026-10-09T11:00')
  await page.getByRole('button',{name:'Salvar tarefa'}).click()
  const deadline=page.getByRole('button',{name:/Tarefa: Tarefa fictícia/})
  const destination=page.getByRole('region',{name:'Dia 2026-10-10',exact:true})
  await deadline.dragTo(destination)
  await expect(page.getByLabel('Prazo (opcional)')).toHaveValue('2026-10-10T11:00')
  await page.getByRole('button',{name:'Cancelar',exact:true}).click()
  await expect(page.getByRole('region',{name:'Dia 2026-10-09',exact:true}).getByRole('button',{name:/Tarefa: Tarefa fictícia/})).toBeVisible()
  await deadline.dragTo(destination)
  await page.getByRole('button',{name:'Salvar tarefa'}).click()
  await expect(destination.getByRole('button',{name:/Tarefa: Tarefa fictícia/})).toBeVisible()
  await page.getByRole('checkbox',{name:'Tarefa fictícia'}).click()
  await page.getByText('Concluídas (1)').click()
  await expect(page.getByRole('checkbox',{name:'Tarefa fictícia'})).toBeChecked()
  await page.getByRole('button',{name:'Novo compromisso',exact:true}).click()
  await page.getByLabel('Título do compromisso').fill('Reunião fictícia')
  await page.getByLabel('Ambiente do compromisso').selectOption('environment-test')
  await page.getByLabel('Fuso do compromisso').selectOption('America/Fortaleza')
  await page.getByLabel('Início',{exact:true}).fill('2026-10-09T09:00')
  await page.getByLabel('Recorrência',{exact:true}).selectOption('weekly')
  await page.getByRole('button',{name:'Salvar compromisso'}).click()
  await expect(page.getByRole('status')).toHaveText('Compromisso salvo.')
  await expect(page.getByText('09/10/2026, 09:00 — 09/10/2026, 09:30')).toBeVisible()
  await page.getByRole('button',{name:'Detalhes / alterar horário'}).click()
  await expect(page.getByRole('radio',{name:'Somente esta ocorrência'})).toBeChecked()
  await page.getByLabel('Título do compromisso').fill('Ocorrência alterada')
  await page.getByRole('button',{name:'Salvar compromisso'}).click()
  await expect(page.getByRole('heading',{name:'Ocorrência alterada'})).toBeVisible()
  await page.getByRole('button',{name:'Próximo',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Reunião fictícia'})).toBeVisible()
  await page.getByRole('button',{name:'Excluir compromisso'}).click()
  await page.getByRole('radio',{name:'Toda a série, incluindo exceções'}).check()
  await page.getByRole('button',{name:'Confirmar exclusão'}).click()
  await expect(page.getByText('Sem compromissos neste período.')).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
})
