// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest'
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest'
import {cleanup,render,screen,waitFor,within} from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import {Connections} from '../src/components/Connections'
import type {ConnectionsRepository,ConnectionsData} from '../src/lib/connections'
const data:ConnectionsData={accounts:[{id:'account',user_id:'user',google_subject:'test',email:'calendar@example.test',created_at:'2026-10-10Z'}],bindings:[],environments:[{id:'env',user_id:'user',name:'Fictício',anchor_words:['um','dois','três'],created_at:'2026-10-10Z',updated_at:'2026-10-10Z'}]}
const calendar={id:'primary',summary:'Calendário fictício',accessRole:'owner'}
let repository:ConnectionsRepository
beforeEach(()=>{repository={activeBindings:vi.fn().mockResolvedValue([]),load:vi.fn().mockResolvedValue(data),connect:vi.fn(),disconnect:vi.fn(),calendars:vi.fn().mockResolvedValue([calendar]),configure:vi.fn().mockResolvedValue({id:'binding'}),sync:vi.fn().mockResolvedValue({imported:1,exported:2,deleted:0,skipped:0,warning:''})};HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new Event('close'))}})
afterEach(cleanup)
describe('seleção Calendar com repositório fictício',()=>{
  it('não salva sem ambiente e confirmação de propagação; cancelar preserva',async()=>{const user=userEvent.setup();render(<Connections repository={repository}/>);await user.click(await screen.findByRole('button',{name:'Escolher calendários'}));expect(screen.getByRole('button',{name:'Selecionar calendário'})).toBeDisabled();await user.selectOptions(screen.getByLabelText('Ambiente para Calendário fictício'),'env');await user.click(screen.getByRole('button',{name:'Selecionar calendário'}));const dialog=screen.getByRole('dialog',{name:'Selecionar calendário?'});expect(within(dialog).getByRole('button',{name:'Confirmar seleção'})).toBeDisabled();await user.click(within(dialog).getByRole('button',{name:'Cancelar'}));expect(repository.configure).not.toHaveBeenCalled();await user.click(screen.getByRole('button',{name:'Selecionar calendário'}));await user.click(screen.getByLabelText('Confirmo a sincronização e a propagação de exclusões'));await user.click(within(dialog).getByRole('button',{name:'Confirmar seleção'}));await waitFor(()=>expect(repository.configure).toHaveBeenCalledWith('account',calendar,'env',true,true))})
  it('falha preserva seleção e permite nova tentativa sem anunciar sucesso',async()=>{const user=userEvent.setup();vi.mocked(repository.configure).mockRejectedValueOnce(new Error('Serviço ausente'));render(<Connections repository={repository}/>);await user.click(await screen.findByRole('button',{name:'Escolher calendários'}));await user.selectOptions(screen.getByLabelText('Ambiente para Calendário fictício'),'env');await user.click(screen.getByRole('button',{name:'Selecionar calendário'}));await user.click(screen.getByLabelText('Confirmo a sincronização e a propagação de exclusões'));await user.click(screen.getByRole('button',{name:'Confirmar seleção'}));const dialog=screen.getByRole('dialog',{name:'Selecionar calendário?'});expect(await within(dialog).findByRole('alert')).toHaveTextContent('Serviço ausente');expect(screen.getByLabelText('Confirmo a sincronização e a propagação de exclusões')).toBeChecked();expect(screen.getByRole('button',{name:'Confirmar seleção'})).toBeEnabled();expect(screen.queryByText(/Calendário selecionado\./)).not.toBeInTheDocument()})
  it('pausar preserva vínculo; sync informa contagens somente após concluir',async()=>{const user=userEvent.setup();vi.mocked(repository.load).mockResolvedValue({...data,bindings:[{id:'binding',user_id:'user',account_id:'account',calendar_id:'primary',calendar_name:'Calendário fictício',environment_id:'env',enabled:true,last_synced_at:null,last_error:null}]});render(<Connections repository={repository}/>);await user.click(await screen.findByRole('button',{name:'Sincronizar agora'}));expect(await screen.findByText(/Sincronização concluída: 1 recebidos, 2 enviados/)).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Escolher calendários'}));expect(screen.getByLabelText('Ambiente para Calendário fictício')).toBeDisabled();await user.click(screen.getByRole('button',{name:'Pausar sincronização'}));expect(repository.configure).toHaveBeenCalledWith('account',calendar,'env',false,false)})
  it('resposta tardia após saída não abre seleção de outra sessão',async()=>{let resolve:(value:typeof calendar[])=>void=()=>{};vi.mocked(repository.calendars).mockReturnValue(new Promise(done=>{resolve=done}));const user=userEvent.setup(),view=render(<Connections repository={repository}/>);await user.click(await screen.findByRole('button',{name:'Escolher calendários'}));view.unmount();resolve([calendar]);expect(screen.queryByRole('heading',{name:'Calendários de calendar@example.test'})).not.toBeInTheDocument()})
})
