import {useEffect,useRef,useState} from 'react'
import type {GoogleAccount} from '../lib/database.types'
import type {ConnectionsData,ConnectionsRepository,WritableCalendar} from '../lib/connections'

export function Connections({repository}:{repository:ConnectionsRepository}){
  const [data,setData]=useState<ConnectionsData>({accounts:[],bindings:[],environments:[]})
  const [error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[attempt,setAttempt]=useState(0)
  const [selected,setSelected]=useState<GoogleAccount|null>(null),[account,setAccount]=useState<GoogleAccount|null>(null),[calendars,setCalendars]=useState<WritableCalendar[]>([])
  const [choices,setChoices]=useState<Record<string,string>>({}),[confirm,setConfirm]=useState<{calendar:WritableCalendar;environment:string}|null>(null),[accepted,setAccepted]=useState(false)
  const disconnectDialog=useRef<HTMLDialogElement>(null),syncDialog=useRef<HTMLDialogElement>(null),mounted=useRef(true)
  useEffect(()=>{mounted.current=true;let active=true;repository.load().then(result=>{if(active){setData(result);setLoaded(true);setError('')}}).catch(cause=>{if(active)setError(cause.message)});return()=>{active=false;mounted.current=false}},[repository,attempt])
  async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setStatus('');try{await action()}catch(cause){if(mounted.current)setError(cause instanceof Error?cause.message:'Não foi possível concluir. Tente novamente.')}finally{if(mounted.current)setBusy(false)}}
  async function refresh(){try{const result=await repository.load();if(mounted.current)setData(result)}catch{if(mounted.current)setError('A ação foi concluída, mas a lista não pôde ser atualizada. Recarregue as conexões.')}}
  async function configure(activate:boolean,calendar:WritableCalendar,environment:string){
    if(!account)return
    await repository.configure(account.id,calendar,environment,activate,activate&&accepted)
    if(mounted.current){syncDialog.current?.close();setConfirm(null);setAccepted(false);setStatus(activate?'Calendário selecionado. Use “Sincronizar agora” para processar as mudanças.':'Sincronização pausada. Eventos preservados.');await refresh()}
  }
  return <section aria-labelledby="connections-heading"><div className="section-heading"><div><p className="eyebrow">Integrações</p><h1 id="connections-heading">Google Calendar</h1><p className="secondary">Escolha o que converge para a sua agenda.</p></div></div>
    <p>Conecte contas Google separadamente do login. Cada calendário selecionado é associado a um ambiente; mudanças usam a versão mais recente e exclusões propagam nos dois sentidos.</p>
    {error&&<p role="alert" className="error">{error}</p>}<p role="status" className="success">{status}</p>
    <div className="actions"><button className="primary" disabled={busy||!loaded} onClick={()=>{void run(async()=>{const url=await repository.connect();if(mounted.current)window.location.assign(url)})}}>{busy?'Aguarde…':'Conectar outra conta Google'}</button><button disabled={busy} onClick={()=>setAttempt(value=>value+1)}>Recarregar conexões</button></div>
    {!loaded&&!error&&<p role="status">Carregando conexões…</p>}
    <ul className="environment-list connection-list">{data.accounts.map(item=><li className="card" key={item.id}><h2>{item.email}</h2><p className="secondary">{data.bindings.filter(binding=>binding.account_id===item.id&&binding.enabled).length} calendários selecionados</p><div className="actions"><button disabled={busy} onClick={()=>{void run(async()=>{const result=await repository.calendars(item.id);if(mounted.current){setAccount(item);setCalendars(result);setChoices(Object.fromEntries(data.bindings.filter(binding=>binding.account_id===item.id).map(binding=>[binding.calendar_id,binding.environment_id??''])))}})}}>Escolher calendários</button><button className="danger" disabled={busy} onClick={()=>{setSelected(item);disconnectDialog.current?.showModal()}}>Desconectar da Allgenda</button></div>
      <ul className="environment-list">{data.bindings.filter(binding=>binding.account_id===item.id).map(binding=><li className="agenda-item" key={binding.id}><h3>{binding.calendar_name}</h3><p><span className="context-badge">{data.environments.find(env=>env.id===binding.environment_id)?.name??'Ambiente removido'}</span> · {binding.enabled?'Selecionado':'Pausado'}</p><p className="secondary">{binding.last_synced_at?`Última conclusão: ${new Date(binding.last_synced_at).toLocaleString('pt-BR')}`:'Ainda não sincronizado.'}</p>{binding.last_error&&<p className="warning">{binding.last_error}</p>}<button disabled={busy||(!binding.enabled&&binding.environment_id!==null)} onClick={()=>{void run(async()=>{const result=await repository.sync(item.id,binding.id);if(mounted.current){setStatus(`Sincronização concluída: ${result.imported} recebidos, ${result.exported} enviados, ${result.deleted} excluídos. ${result.warning}`);await refresh()}})}}>Sincronizar agora</button></li>)}</ul></li>)}</ul>
    {loaded&&!data.accounts.length&&<div className="empty-state"><h2>Suas contas, em um só lugar</h2><p>Nenhuma conta Calendar conectada. Conecte uma conta para escolher seus calendários.</p></div>}
    {account&&<section className="card" aria-label="Calendários disponíveis"><h2>Calendários de {account.email}</h2><p className="secondary">Somente calendários com permissão de edição. Tarefas ficam na Allgenda; esta integração sincroniza compromissos.</p>{!calendars.length&&<p>Nenhum calendário editável disponível.</p>}{!data.environments.length&&<p>Crie um ambiente antes de selecionar calendários.</p>}{calendars.map(calendar=>{const binding=data.bindings.find(item=>item.account_id===account.id&&item.calendar_id===calendar.id);return <div className="agenda-item" key={calendar.id}><h3>{calendar.summary}</h3><label htmlFor={`calendar-${calendar.id}`}>Ambiente para {calendar.summary}</label><select id={`calendar-${calendar.id}`} value={choices[calendar.id]??''} disabled={busy||!!binding} onChange={event=>setChoices({...choices,[calendar.id]:event.target.value})}><option value="">Escolha um ambiente</option>{data.environments.filter(env=>!data.bindings.some(item=>item.environment_id===env.id&&item.id!==binding?.id)).map(env=><option value={env.id} key={env.id}>{env.name}</option>)}</select><div className="actions">{binding?.enabled?<button disabled={busy} onClick={()=>{void run(()=>configure(false,calendar,binding.environment_id!))}}>Pausar sincronização</button>:<button className="primary" disabled={busy||!choices[calendar.id]} onClick={()=>{setConfirm({calendar,environment:choices[calendar.id]});setAccepted(false);syncDialog.current?.showModal()}}>Selecionar calendário</button>}</div></div>})}</section>}
    <dialog ref={syncDialog} aria-labelledby="sync-heading" onCancel={event=>{if(busy)event.preventDefault()}}><h2 id="sync-heading">Selecionar calendário?</h2><p>{confirm?.calendar.summary} → {data.environments.find(env=>env.id===confirm?.environment)?.name}</p><p>Os compromissos deste ambiente e calendário poderão ser criados e alterados nos dois lados. A alteração mais recente prevalece. Excluir em um lado também exclui no outro.</p><p>Eventos de dia inteiro e regras avançadas permanecem no Google.</p><label className="task-check"><input type="checkbox" checked={accepted} disabled={busy} onChange={event=>setAccepted(event.target.checked)}/>Confirmo a sincronização e a propagação de exclusões</label><div className="actions"><button autoFocus disabled={busy} onClick={()=>syncDialog.current?.close()}>Cancelar</button><button className="primary" disabled={busy||!accepted} onClick={()=>{if(confirm)void run(()=>configure(true,confirm.calendar,confirm.environment))}}>Confirmar seleção</button></div>{error&&<p role="alert" className="error">{error}</p>}</dialog>
    <dialog ref={disconnectDialog} aria-labelledby="disconnect-heading" onCancel={event=>{if(busy)event.preventDefault()}}><h2 id="disconnect-heading">Desconectar conta?</h2><p>{selected?.email}</p><p>A conexão e os tokens guardados na Allgenda serão removidos. Os eventos e as permissões no Google serão preservados. Para revogar a autorização no Google, use a página de segurança da sua conta.</p><div className="actions"><button autoFocus disabled={busy} onClick={()=>disconnectDialog.current?.close()}>Cancelar</button><button className="danger" disabled={busy} onClick={()=>{void run(async()=>{if(!selected)return;await repository.disconnect(selected.id);if(mounted.current){disconnectDialog.current?.close();setSelected(null);if(account?.id===selected.id){setAccount(null);setCalendars([])}setStatus('Conta desconectada da Allgenda.');await refresh()}})}}>Confirmar desconexão</button></div>{error&&<p role="alert" className="error">{error}</p>}</dialog>
  </section>
}
