import {createRoot} from 'react-dom/client'
import {useRef} from 'react'
import {Appearance} from './components/Appearance'
import './styles/tokens.css'
import './styles/app.css'
export function DesignPreview(){
  const dialog=useRef<HTMLDialogElement>(null)
  return <><a className="skip-link" href="#main">Ir para o conteúdo</a><header className="site-header"><div><p className="brand">allgenda</p><p className="secondary">Tudo converge aqui</p></div><Appearance/></header><main id="main"><p className="eyebrow">Referência de interface</p><h1>Design system</h1><p>Componentes reais e exemplos fictícios. Cores do handoff aprovado; métricas propostas e tipografia monoespaçada do sistema. Fontes e símbolo finais aguardam os arquivos de marca.</p><p><a href="/">Abrir a Allgenda</a></p>
  <section className="card"><h2>Cores semânticas</h2><div className="swatches">{['background','surface','surface-raised','text-primary','text-secondary','border-control','action-primary','action-hover','success','warning','danger'].map(token=><div className="swatch" key={token}><span className="swatch-color" style={{background:`var(--${token})`}}/><code>{token}</code></div>)}</div></section>
  <div className="gallery-grid"><section className="card"><h2>Ações e estados</h2><div className="actions"><button className="primary">Principal</button><button>Secundário</button><button className="danger">Destrutivo</button><button disabled>Indisponível</button><button disabled aria-busy="true">Salvando…</button></div><p className="secondary">Foco visível por teclado e controles de pelo menos 44 px.</p><p role="status" className="success">Alteração salva. Exemplo de sucesso.</p><p className="warning">Conflito de horário. Confira os compromissos.</p><p role="alert" className="error">Não foi possível salvar. Seus campos foram preservados.</p></section>
  <section className="card"><h2>Campos</h2><label htmlFor="preview-title">Título (obrigatório)</label><input id="preview-title" placeholder="Revisão do projeto"/><label htmlFor="preview-environment">Ambiente (obrigatório)</label><select id="preview-environment"><option>Trabalho · Exemplo fictício</option><option>Pessoal · Exemplo fictício</option></select><label htmlFor="preview-deadline">Prazo (opcional)</label><input id="preview-deadline" type="datetime-local" aria-describedby="preview-help"/><p id="preview-help" className="secondary">Deixe vazio para uma tarefa sem prazo.</p><label htmlFor="preview-invalid">Âncoras inválidas — exemplo</label><input id="preview-invalid" defaultValue="uma, duas" aria-invalid="true" aria-describedby="preview-error"/><p id="preview-error" className="error">Informe pelo menos três palavras distintas.</p></section>
  <section className="card"><h2>Itens e contextos</h2><ul className="environment-list"><li className="agenda-item"><label className="task-check"><input type="checkbox"/>Revisar proposta com título longo e acentuação</label><p><span className="context-badge">Trabalho</span> · Sem prazo</p><div className="actions"><button>Editar tarefa</button><button className="danger">Excluir tarefa</button></div></li></ul><h3>Compromisso recorrente</h3><button className="calendar-event"><strong>Planejamento da semana</strong><span>09:00 — 09:30</span><span>Trabalho · Recorrente</span></button></section>
  <section className="card"><h2>Painéis e diálogos</h2><details open><summary>Pendências</summary><p>Lista expansível, utilizável por toque ou teclado.</p></details><div className="empty-state"><h3>Espaço para o próximo compromisso</h3><p>Nenhum compromisso neste período.</p></div><button onClick={()=>dialog.current?.showModal()}>Abrir confirmação</button></section></div>
  <dialog ref={dialog} aria-labelledby="preview-dialog-heading"><h2 id="preview-dialog-heading">Confirmar alteração?</h2><p>Este diálogo demonstra foco, Escape e retorno ao botão de origem. Nenhum dado é salvo.</p><div className="actions"><button autoFocus onClick={()=>dialog.current?.close()}>Cancelar</button><button className="primary" onClick={()=>dialog.current?.close()}>Confirmar exemplo</button></div></dialog>
  </main><footer><p className="secondary">allgenda · Tudo converge aqui</p></footer></>
}
createRoot(document.getElementById('root')!).render(<DesignPreview/> )
